export const ADD_PRODUCT = "ADD_PRODUCT";
export const INCREMENT_AMOUNT_PRODUCT = "INCREMENT_AMOUNT_PRODUCT";
export const DECREMENT_AMOUNT_PRODUCT = "DECREMENT_AMOUNT_PRODUCT";
export const DELETE_PRODUCT_ITEM_CART = "DELETE_PRODUCT_ITEM_CART";

export  const CLEAR_CART = "CLEAR_CART";