import Toast from "@/components/toast";
import CheckInternet from "@/components/check-internet";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Toast/>
      <body >{children}</body>
    <CheckInternet/>
    </html>
  )
}
