
import "./layout.css";
import Link from "next/link";
import Navigation from "@/components/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    keywords : "hoc Js ,hoc nextJs"
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning={true}>
      <body >
      {children}
      </body>
      </html>
  );
}