import React from "react";
import {Metadata} from "next";
import {Locale} from "next/dist/compiled/@vercel/og/satori";
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({children, params}: { children: React.ReactNode, params : {lang : Locale}}) {
    return (
        <html lang={params.lang}>
        <body>
        <main>{children}</main></body>
        </html>
    )
}
